version: '3.3'

services:
    web:
        image: php:apache
        environment:
            - INFRA=production
            - INFRA_TYPE=docker-composer-3_3
        ports:
            - "8080:80"
        volumes:
            - "./app:/var/www/html"
        networks:
            loggen:
                ipv4_address: 172.23.23.10
    db:
        image: mysql:5.5.61
        volumes:
            - "/var/opt/mysql-loggen:/var/lib/mysql"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=loggen_user
            - MYSQL_PASSWORD=loggen_pass
            - MYSQL_DATABASE=loggen_db
        networks:
            loggen:
                ipv4_address: 172.23.23.20
networks:
    loggen:
        ipam:
            driver: default
            config:
                - subnet: 172.23.23.0/24
