---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gluster-olearning-freewall
spec:
  volumeName: pv-gluster-olearning-freewall
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi

