---
## Patcher la spec du deploiement :
spec:  
  volumes:  
  - name: freewall-db
    secret:  
      secretName: freewall-db-secret
  containers:  
    volumeMounts:  
    - name: freewall-db
      mountPath: /var/secrets/freewall-db-config
    # Tester la création de l'env directement à partir de l'objet secret
    env:  
      - name:  FREEWALL-DB-CONFIG 
        value: "/var/secrets/freewall-db-config/"  
