---
apiVersion: servicecatalog.k8s.io/v1beta1  
kind: ServiceInstance  
metadata:  
  name: app-db  
  namespace: poc  
spec:  
  clusterServiceClassExternalName: mariadb
  clusterServicePlanExternalName: 20mb
---
apiVersion: servicecatalog.k8s.io/v1beta1  
kind: ServiceBinding  
metadata:  
  name: db-secret
  namespace: poc
spec:  
  instanceRef:  
    name: app-db
