apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freewall-app.fullname" . }}
  labels:
    {{- include "freewall-app.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "freewall-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "freewall-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          ports:
            {{- toYaml .Values.ports.nginx | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
          {{- with .Values.volumeMounts.nginx }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: phpfpm
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.phpfpm.repository }}:{{ .Values.image.phpfpm.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.phpfpm.pullPolicy }}
          ports:
            {{- toYaml .Values.ports.phpfpm | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.phpfpm | nindent 12 }}
          {{- with .Values.volumeMounts.phpfpm }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes.application }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
