apiVersion: v1
kind: Service
metadata:
  name: {{ include "freewall-app.fullname" . }}
  labels:
    {{- include "freewall-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  selector:
    {{- include "freewall-app.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: publb
  name: public-lb
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 4443
  selector:
    app: freewall-nginx-lb
  type: LoadBalancer
  loadBalancerIP: 193.250.12.238
